server:
  port: 8080

spring:
  profiles:
    active: mysql # 기본 활성 프로필 설정 (여기서 활성 프로필 변경하며 실행)

# 1) H2 프로필
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:study_batch;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa    # 기본 유저
      password:       # 기본 비밀번호 (없음)
      driver-class-name: org.h2.Driver

  batch:
    jdbc:
      initialize-schema: embedded

# 2) MYSQL 프로필
---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:3307/study_batch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always # Spring Batch 메타 테이블(BATCH_*)이 없으면 자동 생성
      # table-prefix: SYSTEM_ # 기본적으로 BATCH_ 인데, SYSTEM_ 로 변경. 이 때, 기본 스키마(schema-mysql.sql)는 BATCH_로 생성되는데, prefix 만 SYSTEM_로 바꾸면 런타임때 SYSTEM_*을 찾다가 테이블이 없으므로 실패함
      # schema: classpath:batch/schema-mysql-system.sql # 앞의 SYSTEM_을 쓰려면 BATCH_→SYSTEM_로 치환된 스키마 파일을 resources 경로에 직접 넣어야 해서(파일 없으면 부팅 실패) 일단 기본 스키마를 쓰기 위해 주석 처리
    job:
      name: ${job.name:NONE} # Parameter Arguments 에 --job.name=jobConfigurationJob 처럼 설정을 주면, jobConfigurationJob 이 여기 속성에 바인딩 된다.
      # enabled: false # Spring Boot 의 Job 자동 실행 활성화

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true